version: "3.5"

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=task
    ports:
      - "5432:5432"
    volumes:
      - ./configs/init.sql:/docker-entrypoint-initdb.d/init.sql
